# Generated by Django 4.1.3 on 2022-12-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="topic_name",
            new_name="Topic_name",
        ),
    ]
