# Generated by Django 4.1.3 on 2022-12-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_topic_name_topic_topic_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="access",
            old_name="topic_name",
            new_name="Topic_name",
        ),
        migrations.RenameField(
            model_name="webpage",
            old_name="topic_name",
            new_name="Topic_name",
        ),
    ]
